server {
  bind_address = "0.0.0.0"
  bind_port = "8081"
  socket_path = "/run/spire/server.sock"

  trust_domain = "health.secure"
  data_dir = "/run/spire/data"
  log_level = "DEBUG"
}

plugins {
  DataStore "sql" {
    plugin_data {
      database_type = "sqlite3"
      connection_string = "/run/spire/data/datastore.sqlite3"
    }
  }

  NodeAttestor "join_token" {
    plugin_data {}
  }

  KeyManager "memory" {
    plugin_data {}
  }

  UpstreamAuthority "disk" {
    plugin_data {
      key_file_path = "/run/spire/bootstrap/ca.key"
      cert_file_path = "/run/spire/bootstrap/ca.crt"
    }
  }
}